FORMAT: 1A
HOST: http://example.com

# bari1
TODO: Add Description

## Authentication
This API uses OAuth v2 Bearer Token / Personal Access Token for its authentication.

# Group Misc

## V1 Auth Register [/v1/auth/register]

### httpbari1.appv1authregister [POST]
TODO: Add Description
+ Attributes
    + name (string, optional) -

        + Default: salman12
        + Sample: salman12
    + email (string, optional) -

        + Default: salman1345@gmail.com
        + Sample: salman1345@gmail.com
    + password (string, optional) -

        + Default: 123456
        + Sample: 123456
    + userType (string, optional) -

        + Default: 2
        + Sample: 2
    + phone (string, optional) -

        + Default: 01716498393
        + Sample: 01716498393

+ Request (application/x-www-form-urlencoded)



+ Response 200 




## V1 Auth Redeem Referrals [/v1/auth/redeem/referrals]

### httpsbarikoi.tkv1authlogin [POST]
TODO: Add Description
+ Attributes
    + email (string, optional) -

        + Default: barikoi.helper@gmail.com
        + Sample: barikoi.helper@gmail.com
    + password (string, optional) -

        + Default: 1234567
        + Sample: 1234567
    + ref_code (string, optional) -

        + Default: MUVFDD
        + Sample: MUVFDD

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjM0LCJpc3MiOiJodHRwOlwvXC9iYXJpMS5hcHBcL3YxXC9hdXRoXC9sb2dpbiIsImlhdCI6MTQ5NTAxOTg0NSwiZXhwIjoxNDk1MDIzNDQ1LCJuYmYiOjE0OTUwMTk4NDUsImp0aSI6ImMyNTYwNDBmNjczODZhMTY1ZWNkNjAzMWNjZGU1YTUxIn0.eIage7NbBLj09l587mSKRbIUMOwnWaPZaWrI4pfHhUY




+ Response 200 




## V1 Place Get Type [/v1/place/get/type]

### bari1.appv1placegettype [GET]
TODO: Add Description

+ Response 200 




## V1 Place Get Sub Type By TypeName [/v1/place/get/sub/type/{TypeName}]

+ Parameters
    + TypeName (string, required)


### bari1.appv1placegetsubtype [GET]
TODO: Add Description

+ Response 200 




## V1 Place Get By BariKoiCode [/v1/place/get/{BariKoiCode}]

+ Parameters
    + BariKoiCode (string, required)


### bari1.appv1placegetBariKoiCode [GET]
TODO: Add Description

+ Response 200 




## V1 Place Post [/v1/place/post]

### bari1.appv1placepost [POST]
TODO: Add Description
+ Attributes
    + longitude (string, required)

        + Sample: 91.1234
    + latitude (string, required)

        + Sample: 23.5678
    + Address (string, required)

        + Sample: Bashundhra
    + city (string, required)

        + Sample: Dhaka
    + area (string, required)

        + Sample: Vatara
    + postCode (string, required)

        + Sample: 1212
    + pType (string, required)

        + Sample: Food
    + subType (string, required)

        + Sample: Cafe
    + flag (string, required)

        + Sample: 1
    + device_ID (string, required)

    + user_id (string, required)

    + email (string, required)


+ Request (application/x-www-form-urlencoded)



+ Response 200 




## V1 Place Custom Post [/v1/place/custom/post]

### bari1.appv1placecustompost [POST]
TODO: Add Description
+ Attributes
    + longitude (string, required)

        + Sample: 90.1234
    + latitude (string, required)

        + Sample: 23.5678
    + Address (string, required)

        + Sample: Bashundhra
    + city (string, required)

        + Sample: Dhaka
    + area (string, required)

        + Sample: Vatara
    + postCode (string, required)

        + Sample: 1212
    + pType (string, required)

        + Sample: Food
    + subType (string, required)

        + Sample: Cafe
    + flag (string, required)

        + Sample: 1
    + device_ID (string, required)

    + user_id (string, required)

    + email (string, required)

    + uCode (string, required)

        + Sample: MOND0910

+ Request (application/x-www-form-urlencoded)



+ Response 200 




## V1 Place Get ACSW0102 [/v1/place/get/ACSW0102]

### bari1.appv1authplacenewplace [GET]
TODO: Add Description

+ Request 
    + Headers

            Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMzLCJpc3MiOiJodHRwOlwvXC9iYXJpMS5hcHBcL3YxXC9hdXRoXC9sb2dpbiIsImlhdCI6MTQ5NDIzODc3NSwiZXhwIjoxNDk0MjQyMzc1LCJuYmYiOjE0OTQyMzg3NzUsImp0aSI6ImMzOTNiNjVjY2I3OWUzMjlhZjRiNzZhNzE1Yjk5YmJkIn0.sErHtglRShUuU_wMaQ9nwTbhYHkvI7puIj36iLWwfXk




+ Response 200 




## V1 Auth Place Newplacecustom [/v1/auth/place/newplacecustom]

### bari1.appv1authplacenewplacecustom [POST]
TODO: Add Description
+ Attributes
    + longitude (string, required)

        + Sample: 99.1234
    + latitude (string, required)

        + Sample: 23.5678
    + Address (string, required)

        + Sample: Bashundhra
    + city (string, required)

        + Sample: Dhaka
    + area (string, required)

        + Sample: Vatara
    + postCode (string, required)

        + Sample: 1212
    + pType (string, required)

        + Sample: Food
    + subType (string, required)

        + Sample: Cafe
    + flag (string, required)

        + Sample: 1
    + device_ID (string, required)

    + user_id (string, required)

    + email (string, required)

    + uCode (string, required)

        + Sample: MOUD0910

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHBzOlwvXC9iYXJpa29pLnRrXC92MVwvYXV0aFwvbG9naW4iLCJpYXQiOjE0OTQzMDQ5ODYsImV4cCI6MTQ5Njg5Njk4NiwibmJmIjoxNDk0MzA0OTg2LCJqdGkiOiIyMjliYjkzZGY0YmQ2M2M2ZDI3NzA0Mjk4OTk4NzhiZSJ9.0BkpPLn_bP139mR_bhjqGv1tg7S_J1yfaamtETTK_5A




+ Response 200 




## V1 Place Update 399 [/v1/place/update/399]

### bari1.appv1placeupdateid [POST]
TODO: Add Description
+ Attributes
    + longitude (string, required)

        + Sample: 90.1234
    + latitude (string, required)

        + Sample: 23.5678
    + Address (string, required)

        + Sample: Bashundhra R/A
    + city (string, required)

        + Sample: Dhaka
    + area (string, required)

        + Sample: Vatara
    + postCode (string, required)

        + Sample: 1212
    + pType (string, required)

        + Sample: Food
    + subType (string, required)

        + Sample: Restaurent
    + flag (string, required)

        + Sample: 1
    + device_ID (string, required)

    + user_id (string, required)

    + email (string, required)


+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2JhcmkxLmFwcFwvdjFcL2F1dGhcL2xvZ2luIiwiaWF0IjoxNDkyMDcxMzA5LCJleHAiOjE0OTIwNzQ5MDksIm5iZiI6MTQ5MjA3MTMwOSwianRpIjoiOTY3OWFkOTA5YWMyODYzYTUxYmViZTgyNjk2MzRkYzkifQ.i2owWvczKtklCkJmZyR5Iyn9VFBWt4iKkd77UlSSGj8




+ Response 200 




## V1 Auth Place Update [/v1/auth/place/update/]

### bari1.appv1authplaceupdateid [POST]
TODO: Add Description
+ Attributes
    + longitude (string, required)

        + Sample: 90.1234
    + latitude (string, required)

        + Sample: 23.5678
    + Address (string, required)

        + Sample: Bashundhra R/A
    + city (string, required)

        + Sample: Dhaka
    + area (string, required)

        + Sample: Vatara
    + postCode (string, required)

        + Sample: 1212
    + pType (string, required)

        + Sample: Food
    + subType (string, required)

        + Sample: Restaurent
    + flag (string, required)

        + Sample: 1
    + device_ID (string, required)

    + user_id (string, required)

    + email (string, required)


+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2JhcmkxLmFwcFwvdjFcL2F1dGhcL2xvZ2luIiwiaWF0IjoxNDkyMDcxMzA5LCJleHAiOjE0OTIwNzQ5MDksIm5iZiI6MTQ5MjA3MTMwOSwianRpIjoiOTY3OWFkOTA5YWMyODYzYTUxYmViZTgyNjk2MzRkYzkifQ.i2owWvczKtklCkJmZyR5Iyn9VFBWt4iKkd77UlSSGj8




+ Response 200 




## V1 Auth Savedplacebyuid [/v1/auth/savedplacebyuid]

### httpbari1.appv1authsavedplacebyuid [GET]
TODO: Add Description

+ Request 
    + Headers

            Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2JhcmkxLmFwcFwvdjFcL2F1dGhcL2xvZ2luIiwiaWF0IjoxNDkyMDc2Mzg3LCJleHAiOjE0OTIwNzk5ODcsIm5iZiI6MTQ5MjA3NjM4NywianRpIjoiM2E3YmRhOTE0Y2FmMjUxNGU2NGQzMmE2MzBiNTE1OWMifQ.akF1zQf7H913Yo85j4u6nDcjAvMqisFfc95Jryl1JwM




+ Response 200 




## V1 Auth Save Place [/v1/auth/save/place]

### httpbari1.appv1authsaveplace [POST]
TODO: Add Description
+ Attributes
    + email (string, optional) -

        + Default: tayef56@yahoo.com
        + Sample: tayef56@yahoo.com
    + password (string, optional) -

        + Default: 123456
        + Sample: 123456
    + pid (string, optional) -

        + Default: 398
        + Sample: 398

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2JhcmkxLmFwcFwvdjFcL2F1dGhcL2xvZ2luIiwiaWF0IjoxNDkyMDc2Mzg3LCJleHAiOjE0OTIwNzk5ODcsIm5iZiI6MTQ5MjA3NjM4NywianRpIjoiM2E3YmRhOTE0Y2FmMjUxNGU2NGQzMmE2MzBiNTE1OWMifQ.akF1zQf7H913Yo85j4u6nDcjAvMqisFfc95Jryl1JwM




+ Response 200 




## V1 Auth Saved Place Delete [/v1/auth/saved/place/delete/]

### httpbari1.appv1authsavedplacedelete [GET]
TODO: Add Description

+ Request 
    + Headers

            Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2JhcmkxLmFwcFwvdjFcL2F1dGhcL2xvZ2luIiwiaWF0IjoxNDkyMDc2Mzg3LCJleHAiOjE0OTIwNzk5ODcsIm5iZiI6MTQ5MjA3NjM4NywianRpIjoiM2E3YmRhOTE0Y2FmMjUxNGU2NGQzMmE2MzBiNTE1OWMifQ.akF1zQf7H913Yo85j4u6nDcjAvMqisFfc95Jryl1JwM




+ Response 200 



