<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'System' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Net' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Namshi\\JOSE' => array($vendorDir . '/namshi/jose/src'),
    'Math' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Maatwebsite\\Excel\\' => array($vendorDir . '/maatwebsite/excel/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JakubOnderka\\PhpConsoleColor' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'File' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Crypt' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Cron' => array($vendorDir . '/mtdowling/cron-expression/src'),
);
